// AUTO-GENERATED by scripts/sync-lta-data.mjs — do not edit by hand.
// Source: LTA Datamall — "COE Bidding Results"
// https://datamall.lta.gov.sg/content/datamall/en/static-data.html#Vehicle%20Registration
//
// Raw CSV text extracted from the LTA zip, parsed at request time by the
// same parseCoeCsv() used for manual uploads — one parser, one set of rules.
// Empty until the monthly sync workflow (.github/workflows/sync-lta-data.yml)
// runs for the first time. Until then, src/lib/coe.functions.ts falls back
// to a live fetch from data.gov.sg.
export const LIVE_COE_UPDATED_AT: string | null = null;
export const LIVE_COE_CSV_TEXT: string = "";
