// AUTO-GENERATED by scripts/sync-lta-data.mjs — do not edit by hand.
// Source: LTA Datamall — "Annual Motor Vehicle Population by Vehicle Type"
// https://datamall.lta.gov.sg/content/datamall/en/static-data.html#Vehicle%20Population
//
// Empty until the monthly sync workflow (.github/workflows/sync-lta-data.yml)
// runs for the first time. Until then, the vehicle population route falls
// back to the embedded DEFAULT_VEHICLE_POPULATION_CSV snapshot.
export const LIVE_VEHICLE_POPULATION_UPDATED_AT: string | null = null;
export const LIVE_VEHICLE_POPULATION_CSV: string = "";
